### ISSUE TITLE
Results on PECAN dataset?

### ISSUE THREAD

**Issue by aggelos-michael-papadopoulos** [WangZhiwei9/MIPE#2]
Are there any results on PECAN dataset? Paragraph model is the current state-of-art on this official paratope prediction dataset. But i do not see your results on this database which has an official train/val/test split based on homology/sequence similarity etc...

**Comment by WangZhiwei9** [comment]
Thank you for your question.
Given the increasing volume of data on antigens and antibodies, we adopted the construction method of PECAN and obtained the most recent dataset from the SAbDab database as our dataset.
For information about our data collection and processing, please refer to Section 4.1 of our paper.

**Comment by aggelos-michael-papadopoulos** [comment]
Ok i see. Thank you
